const CartActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  SET_CART: "SET_CART",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
  REMOVE_ITEM: " REMOVE_ITEM",
  CLEAR_CART: "CLEAR_CART",
};

export default CartActionTypes;
