const ProductActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_LOADING: "SET_PRODUCTS_LOADING",
  SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",
  SET_CATEGORY: "SET_CATEGORY",
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
  SET_SORTING: "SET_SORTING",
  SET_LIMIT: "SET_LIMIT",
  SET_PAGE: "SET_PAGE",
};

export default ProductActionTypes;
